name: TestNode.js CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test

  deploy:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test SSH Connection
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "echo SSH connection successful"
          rm private_key.pem

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to Ubuntu Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP_TEST }}
          SERVER_USER: ${{ secrets.SERVER_USER_TEST }}
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no -r ./dist $SERVER_USER@$SERVER_IP:/home/kimlrlr

          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
            cd /home/kimlrlr
            npm install --production
            pm2 restart all
          EOF

      - name: Clean up
        run: rm private_key.pem
