name: TestNode.js CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test

  deploy:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup SSH key
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      # - name: Add server to known_hosts
      #   run: |
      #     ssh-keyscan -H -p 9922 127.0.0.1 >> ~/.ssh/known_hosts
      # - name: SSH to Ubuntu Server and create folders
      #   run: |
      #     ssh -i ~/.ssh/id_rsa -p ${{ secrets.PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /home/github/test/test1 && mkdir -p /home/github/test/test2"
      # - name: SSH Remote Commands
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.PORT }}
          timeout: 40s # 30초 기본
          script: |
            ssh -o StrictHostKeyChecking=no -p 9922 kimlrlr@192.168.1.8 'cd /home/kimlrlr/CI-CD-test && git pull'

        # env:
        #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
        #   SERVER_IP: ${{ secrets.HOST_IP }}
        #   SERVER_USER: ${{ secrets.SERVER_USER }}
        # run: |
        #   ssh -o StrictHostKeyChecking=no -p 9922 kimlrlr@192.168.1.8 'cd /home/kimlrlr/CI-CD-test && git pull'

      # - name: Test SSH Connection
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
      #     SERVER_IP: ${{ secrets.SERVER_IP_TEST }}
      #     SERVER_USER: ${{ secrets.SERVER_USER_TEST }}
      #   run: |
      #     echo "$SSH_PRIVATE_KEY" > private_key.pem
      #     chmod 600 private_key.pem
      #     ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "echo SSH connection successful"
      #     rm private_key.pem

      # - name: Deploy to Ubuntu Server
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
      #     SERVER_IP: ${{ secrets.SERVER_IP_TEST }}
      #     SERVER_USER: ${{ secrets.SERVER_USER_TEST }}
      #   run: |
      #     echo "$SSH_PRIVATE_KEY" > private_key.pem
      #     chmod 600 private_key.pem

      #     scp -i private_key.pem -o StrictHostKeyChecking=no -r ./dist $SERVER_USER@$SERVER_IP:/home/kimlrlr

      #     ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
      #       cd /home/kimlrlr
      #       npm install --production
      #       pm2 restart all
      #     EOF

      #     rm private_key.pem

      #..
